### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by machitgarha** [panzi/formatstring#1]
Without a license, using this library should be illegal. Please add one. I recommend Apache License 2.0 or one of the LGPLs.

**Comment by panzi** [comment]
I should add to the README: this is more like a proof of concept, not used by anyone in any production environment, no tests, not maintained and probably inefficient. So I don't think you want to use it.

**Comment by panzi** [comment]
Added MIT license in commit 8c7cb73cd69e29c3289924de7bb51e28cd032f79 anyway. :D

**Comment by machitgarha** [comment]
@panzi Great!

However the stars show this is something more than a proof of concept or testing, but something close to complete.

**Comment by panzi** [comment]
When deciding if one should use a certain library I think one should look at if there is (good) documentation (there is absolutely zero here), if there is good test coverage, and how actively it is maintained (this isn't). What do the stars even mean? Probably just people "bookmarking" this repo because the concept interesting to them, but not because they're actually using it, I'd guess. Or do you know anyone who uses this library? :D

**Comment by machitgarha** [comment]
@panzi Right. But, if your library had a license when I was searching for such a thing, then I would choose yours.

I think a repository with more stars tend to be generally better than one with fewer stars, both not having well-written documentation, not actively maintained and not unit-tested well. Plus, I guess many stars are just because of the READMEs, not how useful or good a repository is. I don't mean your library is bad or so, but I mean most people like me look at the README files to know the usefulness of a library. These are why I was (and am) interested in using this one over the others.
